# Generated by Django 4.0.5 on 2022-07-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    # This tells django that this is first migration to be excuted ever in this app
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
